# Generated by Django 4.2.30 on 2026-04-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('institution', 'Institution')], max_length=50),
        ),
    ]
