# Generated by Django 4.2.30 on 2026-05-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
