# Generated by Django 4.2.30 on 2026-05-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
