# Generated by Django 4.2.30 on 2026-05-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_is_ai_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_ai_generated',
        ),
    ]
