# Generated by Django 4.2.30 on 2026-04-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('correct_tf_answer__isnull', False), ('question_type', 'tf')), ('question_type', 'mcq'), _connector='OR'), name='tf_answer_required'),
        ),
    ]
