# Generated by Django 4.2.30 on 2026-04-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_tf_answer_required'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='tf_answer_required',
        ),
    ]
