# Generated by Django 4.2.30 on 2026-04-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_tf_answer_required'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('correct_tf_answer__isnull', False), ('question_type', 'tf')), ('question_type', 'mcq'), _connector='OR'), name='tf_answer_required'),
        ),
    ]
